#consideram ca folderul are urmtoarea structura

# app.py
# requirements.txt
# compose.yaml

services:
  redis:
    image: redis
    ports:
      - "6379:6379" 6379
  python:
    build: .
    ports:
      - "8000:8000"
    volumes:
    depends_on:
      - redis

services:
  redis:
    image:
    volumes:
    build:
    container_name:
    depends_on:
    environment:
    command:
    ports:
     - "8000:8000"

