apiVersion: app/v1
type: Deployment
metadata:
  name:
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80

kubectl get deployments
kubectl get pods


kubectl edit 



    
    
  